### ISSUE TITLE
LayoutAnimation not working in Android

### ISSUE THREAD

**Issue by ngohungphuc** [ngohungphuc/Mobile-Development#2]
If using `LayoutAnimation.spring()` in Android need to add

```js
import {
  UIManager,
  LayoutAnimation,
  Platform,
} from "react-native";
```

and 
```js
 if (Platform.OS === "android") {
      UIManager.setLayoutAnimationEnabledExperimental &&
        UIManager.setLayoutAnimationEnabledExperimental(true);
      LayoutAnimation.spring();
    }
```

**Comment by deepak-nagar** [comment]
thanks  ngohungphuc

**Comment by ngohungphuc** [comment]
@deepak-nagar no problem

**Comment by deepak-nagar** [comment]
You have idea how to build apk in react -native app ?
in physical mobile

**Comment by vitto-moz** [comment]
Thanks for example. One more question. If we use LayoutAnimation in several components - should we call 
`UIManager.setLayoutAnimationEnabledExperimental(true) `
in each component, or we can just call it once?

**Comment by ngohungphuc** [comment]
@vitto-moz I think you need to call in each component

**Comment by gbalduzzi** [comment]
@vitto-moz you can call it just once in your `index.js` main file

**Comment by ShivamJoker** [comment]
Please add this example in docs
